version: "3.1"
services:
  db-dev:
    container_name: db-dev
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=MySQL
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=db4dev$
    ports:
      - 3306:3306
    volumes:
      - dbdev:/var/lib/mysql
    networks:
      - dev_net
  api-dev:
    container_name: api-dev
    restart: always
    depends_on:
      - db-dev
    image: test
    ports:
      - 8081:4000
    environment:
      - DB_HOST=db-dev
      - DB_USER=admin
      - DB_PASSWORD=db4dev$
      - DB_NAME=MySQL
      - DB_PORT=3306
    networks:
      - dev_net
  db-test:
    container_name: db-test
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=MySQL
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=db4test$
    ports:
      - 3307:3306
    volumes:
      - dbtest:/var/lib/mysql
    networks:
      - test_net
  api-test:
    container_name: api-test
    restart: always
    depends_on:
      - db-test
    image: test
    ports:
      - 8082:4000
    environment:
      - DB_HOST=db-test
      - DB_USER=admin
      - DB_PASSWORD=db4test$
      - DB_NAME=MySQL
      - DB_PORT=3306
    networks:
      - test_net
volumes:
  dbdev:
  dbtest:

networks:
  dev_net:
  test_net:
